config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'

  resources :categories do
    resources :tasks
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, dependent: :destroy

    validates :category, presence: true, :uniqueness => {:scope => :user_id}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  validates :title, presence: true, length: { minimum: 1}
  validates :details, length: { maximum: 250 }

  scope :with_no_date, -> { where(:date => nil, :completed => false) }
  scope :with_upcoming, -> { where.not(:date => Time.zone.today).where.not('date < ?', Time.zone.today).where('date > ?', Time.zone.today.end_of_week).where(:completed => false) }
  scope :with_this_week, -> { where.not(:date => Time.zone.today).where.not('date < ?', Time.zone.today).where(:date => Time.zone.today.beginning_of_week...Time.zone.today.end_of_week, :completed => false) }
  scope :with_today, -> { where(:date => Time.zone.today, :completed => false) }
  scope :with_overdue, -> { where('date < ?', Time.zone.today).where(:completed => false) }
  scope :with_done, -> { where(:completed => true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :categories, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = current_user.categories
  end

  # GET /categories/1
  def show
    @no_date = @category.tasks.with_no_date
    @upcoming = @category.tasks.with_upcoming
    @this_week = @category.tasks.with_this_week
    @today = @category.tasks.with_today
    @overdue = @category.tasks.with_overdue
    @done = @category.tasks.with_done
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :load_category, only: [ :index, :new, :create, :edit, :show, :update, :destroy,]
    before_action :load_task, only: [ :show, :edit, :update, :destroy]
    def index
        redirect_to category_path(@category)
    end

    def show
    end

    def new
        @task = Task.new
    end

    def edit
    end

    def create
        @task = @category.tasks.build(task_params)
        if @task.save 
            redirect_to category_path(@category), notice: 'Task was successfully created.'
        else
            render :new
        end
    end


    def update
        if @task.update(task_params)
            redirect_to category_path(@category), notice: 'Task was successfully updated.'
        else
            render :edit
        end
    end

    def destroy
        @task.destroy
        redirect_to category_path(@category), notice: 'Task was successfully destroyed.'
    end

    private
    def load_category
        @category = current_user.categories.find(params[:category_id])
    end

    def load_task
        @task = @category.tasks.find(params[:id])
    end

    def task_params
            params.require(:task).permit(:title, :details, :completed, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block border outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.text_field :user_id, value: current_user.id, type: :hidden %>

  <div class="inline">
    <%= form.submit class: "py-3 px-5 bg-black rounded-lg text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <div class="flex items-center border-b pb-3">
    <h1 class="font-bold text-3xl">Categories</h1>
    <%= link_to 'New Category', new_category_path, class: "rounded-lg py-3 px-5 ml-2 bg-gray-100 font-medium inline" %>
  </div>

  <div id="categories" class="w-11/12 m-auto">
    <% @categories.each do |category| %>
      <div id="<%= dom_id category %>" class="flex justify-between items-center border-b py-2.5">
      <%= link_to category.category, category, class: "w-8/12 text-xl" %>
      <div>
        <%= link_to 'Edit', edit_category_path(category), class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium" %>
        <%= button_to 'Delete', category_path(category), method: :delete, data: { confirm: "Are you sure?"}, class: "rounded-lg py-3 px-5 ml-2 bg-gray-100 font-medium inline" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div>
  <div>
    <div class="border-b py-3 flex justify-between items-baseline">
      <h2 class="text-xl"><%= @category.category %></h2>
      <div>
        <%= link_to 'Create a new task', new_category_task_path(@category.id), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
        <%= link_to 'Back to categories', categories_path, class: "mt-5 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    </div>

    <div class="flex justify-between mt-5 items-baseline">
      <div>
        <h3 class="rounded-lg py-3 px-5 bg-gray-100 font-medium">No Date</h3>
        <% @no_date.each do |task| %>
          <div class="mt-2.5">
            <%= form_with model: [@category, task], class: "inline"  do |f| %>
              <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
            <% end %>
            <%= link_to task.title, category_task_path(task.category_id, task.id) %>
          </div>
        <% end %>
      </div>
      <div>
        <h3 class="rounded-lg py-3 px-5 bg-blue-300 font-medium inline-block">Upcoming</h3>
        <% @upcoming.each do |task| %>
          <div class="mt-2.5">
            <%= form_with model: [@category, task], class: "inline"  do |f| %>
              <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
            <% end %>
            <%= link_to task.title, category_task_path(task.category_id, task.id) %>
          </div>
        <% end %>
      </div>
      <div>
        <h3 class="rounded-lg py-3 px-5 bg-yellow-300 font-medium inline-block">This week</h3>
        <% @this_week.each do |task| %>
          <div class="mt-2.5">
            <%= form_with model: [@category, task], class: "inline"  do |f| %>
              <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
            <% end %>
            <%= link_to task.title, category_task_path(task.category_id, task.id) %>
          </div>
        <% end %>
      </div>
      <div>
        <h3 class="rounded-lg py-3 px-5 bg-orange-300 font-medium inline-block">Today</h3>
        <% @today.each do |task| %>
          <div class="mt-2.5">
            <%= form_with model: [@category, task], class: "inline"  do |f| %>
              <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
            <% end %>
            <%= link_to task.title, category_task_path(task.category_id, task.id) %>
          </div>
        <% end %>
      </div>
      <div>
        <h3 class="rounded-lg py-3 px-5 bg-red-300 font-medium inline-block">Overdue</h3>
        <% @overdue.each do |task| %>
          <div class="mt-2.5">
            <%= form_with model: [@category, task], class: "inline"  do |f| %>
              <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
            <% end %>
            <%= link_to task.title, category_task_path(task.category_id, task.id) %>
          </div>
        <% end %>
      </div>
      <div>
      <h3 class="rounded-lg py-3 px-5 bg-green-300 font-medium inline-block">Done</h3>
      <% @done.each do |task| %>
        <div class="mt-2.5">
          <%= form_with model: [@category, task], class: "inline"  do |f| %>
            <%= f.check_box "completed", { checked: task.completed, onchange: "this.form.submit();" } %>
          <% end %>
          <%= link_to task.title, category_task_path(task.category_id, task.id) %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>Quest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="font-source m-auto container h-full">
    <nav class="p-5 flex justify-between items-center">
      <a href="/">
        <h1 class="text-5xl font-black">Quest</h1>
      </a>
      <div>
        <% if user_signed_in? %>
          <%= link_to 'Profile Settings', edit_user_registration_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium"%>
          <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium"%>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium"%>
          <%= link_to 'Login', new_user_session_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium"%>
        <% end %>
      </div>
    </nav>
    <main class="px-10">
    <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [@category, @task] do |form| %>
    <% if @task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="my-5">
        <%= form.label :title %>
        <%= form.text_field :title,  class: "block border outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
        <%= form.label :details %>
        <%= form.text_area :details,  class: "block border outline-none px-3 py-2 mt-2 w-full" %>
    </div>
    <div class="my-5">
        <%= form.label :completed %>
        <%= form.check_box :completed %>
    </div>
    <div class="my-5">
        <%= form.label :date %>
        <%= form.date_field :date, class: "block border outline-none px-3 py-2 mt-2" %>
    </div>
    
    <%= form.submit class: "rounded-lg py-3 px-5 bg-black text-white inline-block font-medium cursor-pointer" %>
    <%= link_to "Cancel", :back, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium cursor-pointer" %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<div class="flex items-baseline justify-between border-b pb-2.5">
    <div class="flex items-baseline">
        <h2 class="text-3xl"><%= @task.title %></h2>
        <% if @task.date %>
            <p class="ml-3">Due: <%= @task.date.strftime('%B %d, %Y') %></p>
        <% end %>
        <% if @task.completed %>
            <p class="ml-3">Completed</p>
        <% else %>
            <p class="ml-3">Not Completed</p>
        <% end %>
    </div>
    <div>
        <%= link_to 'Back to Category Page', category_path(@category), class: "rounded-lg py-3 px-5 bg-gray-100 inline font-medium" %>
        <%= link_to 'Edit', edit_category_task_path(@task.category, @task), class: "rounded-lg py-3 px-5 ml-2 bg-gray-100 inline font-medium" %>
        <%= button_to 'Delete', [@task.category, @task], method: :delete, data: { confirm: "Are you sure?"}, class: "rounded-lg py-3 px-5 ml-2 bg-gray-100 font-medium inline" %>
    </div>
</div>
</div>
<div class="w-11/12 m-auto mt-3 flex items-baseline">
    <h3 class="text-xl mb-3">Details: </h3>
    <p class="ml-5"><%= @task.details %></p>
<div>